export enum ErrorCode {
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UPLOAD_INVALID_TYPE = 'UPLOAD_INVALID_TYPE',
  UPLOAD_TOO_LARGE = 'UPLOAD_TOO_LARGE',
  SPIN_FRAME_INDEX_CONFLICT = 'SPIN_FRAME_INDEX_CONFLICT',
  DRAFT_IMAGE_PROCESSING_FAILED = 'DRAFT_IMAGE_PROCESSING_FAILED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}

export const HTTP_STATUS_MAP: Record<ErrorCode, number> = {
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: 401,
  [ErrorCode.AUTH_TOKEN_EXPIRED]: 401,
  [ErrorCode.AUTH_FORBIDDEN]: 403,
  [ErrorCode.VALIDATION_ERROR]: 422,
  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.UPLOAD_INVALID_TYPE]: 400,
  [ErrorCode.UPLOAD_TOO_LARGE]: 413,
  [ErrorCode.SPIN_FRAME_INDEX_CONFLICT]: 409,
  [ErrorCode.DRAFT_IMAGE_PROCESSING_FAILED]: 500,
  [ErrorCode.INTERNAL_SERVER_ERROR]: 500,
};

