import type { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  container: {
    padding: '20px 16px 32px',
    maxWidth: '1280px',
    margin: '0 auto',
    boxSizing: 'border-box',
  },
  header: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '24px' },
  title: { fontSize: '28px', fontWeight: 800, margin: 0, color: '#0f172a', letterSpacing: '-0.02em', lineHeight: 1.15 },
  createBtn: {
    padding: '8px 16px', background: '#6366f1', color: '#fff',
    border: 'none', borderRadius: '8px', cursor: 'pointer', fontWeight: 600,
  },
  form: {
    background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.1)',
    borderRadius: '12px', padding: '20px', marginBottom: '24px',
    display: 'flex', flexDirection: 'column', gap: '12px',
  },
  formRow: { display: 'flex', flexDirection: 'column', gap: '4px' },
  label: { fontSize: '13px', fontWeight: 500, color: '#d1d5db' },
  input: {
    padding: '8px 12px', background: 'rgba(255,255,255,0.06)',
    border: '1px solid rgba(255,255,255,0.15)', borderRadius: '8px',
    color: 'inherit', fontSize: '14px',
  },
  grid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: '16px' },
  card: {
    background: '#ffffff',
    border: '1px solid #e2e8f0',
    borderRadius: '14px',
    padding: '16px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    minHeight: '170px',
    boxShadow: '0 6px 18px rgba(15,23,42,0.08)',
  },
  cardHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    paddingBottom: '8px',
    borderBottom: '1px solid #f1f5f9',
  },
  dot: { width: '10px', height: '10px', borderRadius: '50%', flexShrink: 0 },
  shopName: { fontSize: '16px', flex: 1 },
  slug: { fontSize: '11px', background: '#f8fafc', color: '#475569', padding: '2px 6px', borderRadius: '4px' },
  meta: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '8px',
    fontSize: '13px',
    color: '#64748b',
    alignItems: 'center',
  },
  metaClickable: {
    cursor: 'pointer',
    background: '#f8fafc',
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    padding: '6px 8px',
    font: 'inherit',
    color: 'inherit',
    fontSize: '13px',
    textDecoration: 'underline dotted',
    textUnderlineOffset: '3px',
    textAlign: 'left',
  },
  itemsToolbar: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '4px',
  },
  itemsPageSizeSelect: {
    padding: '8px 10px',
    borderRadius: '8px',
    border: '1px solid rgba(0,0,0,0.15)',
    fontSize: '13px',
    color: '#111827',
    background: '#fff',
  },
  shopItemsTableWrap: {
    border: '1px solid rgba(0,0,0,0.08)',
    borderRadius: '8px',
    overflow: 'auto',
    maxHeight: '50vh',
  },
  shopItemsTable: {
    width: '100%',
    borderCollapse: 'collapse' as const,
    background: '#fff',
  },
  shopItemsTh: {
    textAlign: 'left' as const,
    fontSize: '12px',
    fontWeight: 700,
    color: '#4b5563',
    padding: '10px 12px',
    background: '#f9fafb',
    borderBottom: '1px solid rgba(0,0,0,0.08)',
  },
  shopItemsTd: {
    padding: '10px 12px',
    fontSize: '13px',
    color: '#111827',
    borderBottom: '1px solid rgba(0,0,0,0.06)',
    verticalAlign: 'middle' as const,
  },
  shopItemThumb: {
    width: '48px',
    height: '48px',
    objectFit: 'cover' as const,
    borderRadius: '6px',
    border: '1px solid rgba(0,0,0,0.08)',
  },
  shopItemNoImage: {
    width: '48px',
    height: '48px',
    borderRadius: '6px',
    border: '1px dashed rgba(0,0,0,0.2)',
    color: '#9ca3af',
    fontSize: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  itemsPaginationRow: {
    marginTop: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
  },
  itemsPaginationBtns: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  membersListBox: {
    maxHeight: 'min(360px, 50vh)',
    overflowY: 'auto',
    border: '1px solid rgba(0,0,0,0.08)',
    borderRadius: '8px',
    background: '#fafafa',
  },
  memberRow: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '12px',
    padding: '12px 14px',
    borderBottom: '1px solid rgba(0,0,0,0.06)',
  },
  memberRowMain: { flex: 1, minWidth: 0 },
  memberName: { fontSize: '14px', fontWeight: 600, color: '#111827', marginBottom: '2px' },
  memberEmail: { fontSize: '13px', color: '#374151', wordBreak: 'break-all' as const },
  memberRole: { fontSize: '12px', color: '#6b7280', marginTop: '4px' },
  memberInactiveBadge: { color: '#b91c1c', fontWeight: 500 },
  memberRowActions: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '8px',
    flexShrink: 0,
  },
  memberResetBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    flexShrink: 0,
    padding: '6px 10px',
    fontSize: '12px',
    fontWeight: 600,
    color: '#4f46e5',
    background: '#ffffff',
    border: '1px solid #6366f1',
    borderRadius: '8px',
    cursor: 'pointer',
  },
  memberLockBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    flexShrink: 0,
    padding: '6px 10px',
    fontSize: '12px',
    fontWeight: 600,
    color: '#b91c1c',
    background: '#ffffff',
    border: '1px solid #dc2626',
    borderRadius: '8px',
    cursor: 'pointer',
  },
  memberUnlockBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    flexShrink: 0,
    padding: '6px 10px',
    fontSize: '12px',
    fontWeight: 600,
    color: '#15803d',
    background: '#ffffff',
    border: '1px solid #22c55e',
    borderRadius: '8px',
    cursor: 'pointer',
  },
  cardActionsRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '8px',
    marginTop: '4px',
  },
  cardActionsLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  iconBtnEdit: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '36px',
    height: '36px',
    padding: 0,
    background: 'transparent',
    color: '#6366f1',
    border: '1px solid #6366f1',
    borderRadius: '8px',
    cursor: 'pointer',
  },
  iconBtnDanger: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '36px',
    height: '36px',
    padding: 0,
    background: 'transparent',
    color: '#ef4444',
    border: '1px solid #ef4444',
    borderRadius: '8px',
    cursor: 'pointer',
  },
  iconBtnSuccess: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '36px',
    height: '36px',
    padding: 0,
    background: 'transparent',
    color: '#22c55e',
    border: '1px solid #22c55e',
    borderRadius: '8px',
    cursor: 'pointer',
  },
  inactiveLabel: { fontSize: '12px', color: '#9ca3af' },
  error: { color: '#ef4444', marginBottom: '16px' },
  success: { color: '#22c55e', marginBottom: '16px' },
  activateBtn: {
    padding: '6px 12px',
    background: 'transparent',
    color: '#22c55e',
    border: '1px solid #22c55e',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '12px',
    alignSelf: 'flex-start',
  },
  memberBox: {
    marginTop: '12px',
    paddingTop: '12px',
    borderTop: '1px solid rgba(255,255,255,0.12)',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(255,255,255,0.9)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: '16px',
  },
  modalOverlayNested: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(17,24,39,0.4)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1100,
    padding: '16px',
  },
  modal: {
    width: '100%',
    maxWidth: '520px',
    background: '#ffffff',
    border: '1px solid rgba(0,0,0,0.1)',
    borderRadius: '12px',
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  modalLabel: { fontSize: '13px', fontWeight: 500, color: '#111827' },
  modalLabelInvalid: { color: '#b91c1c' },
  modalFieldError: {
    display: 'block',
    fontSize: '12px',
    fontWeight: 500,
    color: '#b91c1c',
    marginTop: '-4px',
    marginBottom: '2px',
    lineHeight: 1.35,
  },
  modalInput: {
    padding: '8px 12px',
    background: '#ffffff',
    border: '1px solid rgba(0,0,0,0.15)',
    borderRadius: '8px',
    color: '#111827',
    fontSize: '14px',
  },
  modalInputInvalid: {
    border: '1px solid #dc2626',
    outlineColor: '#dc2626',
  },
  passwordStrengthMeter: {
    display: 'flex',
    gap: '4px',
    marginTop: '2px',
    marginBottom: '2px',
  },
  passwordStrengthSegment: {
    flex: 1,
    height: '4px',
    borderRadius: '2px',
    transition: 'background 0.15s ease',
  },
  modalTitle: { fontSize: '18px', fontWeight: 700, color: '#111827' },
  modalError: { color: '#b91c1c', fontSize: '14px', margin: 0, lineHeight: 1.4 },
  modalHint: {
    fontSize: '12px',
    color: '#6b7280',
    margin: 0,
    lineHeight: 1.45,
  },
  modalCode: {
    fontSize: '11px',
    background: '#f3f4f6',
    padding: '2px 6px',
    borderRadius: '4px',
    color: '#111827',
  },
  modalActions: { display: 'flex', gap: '12px', justifyContent: 'flex-end', marginTop: '8px' },
  modalCancelBtn: {
    padding: '8px 12px',
    background: '#ffffff',
    color: '#111827',
    border: '1px solid rgba(0,0,0,0.15)',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
  },
  modalConfirmBtn: {
    padding: '8px 12px',
    background: '#22c55e',
    color: '#fff',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
  },
};
